version: "3.8"

services:
  database:
    container_name: database
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=beer_db
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  opa:
    container_name: opa
    image: openpolicyagent/opa:0.63.0
    ports:
      - "8181:8181"
    volumes:
      - ./policy.rego:/policy/policy.rego
      - ./private.key:/private.key
      - ./public.crt:/public.crt
    command: ["run", "--server",
              "--log-level", "debug",
              "--tls-cert-file", "public.crt",
              "--tls-private-key-file", "private.key",
              "/policy"]