version: "3.8"

services:
  opa:
    image: openpolicyagent/opa
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
    volumes:
      - ./policy.rego:/policy.rego

  database:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=opa-db
